--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13.04.2024 16:53:17
-- Server version: 8.0.36
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS main;

CREATE DATABASE IF NOT EXISTS main
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE main;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id int NOT NULL AUTO_INCREMENT,
  email varchar(130) NOT NULL,
  phone varchar(15) NOT NULL,
  name varchar(45) NOT NULL,
  second_name varchar(45) NOT NULL,
  password varchar(255) NOT NULL,
  region varchar(50) DEFAULT NULL,
  city varchar(50) DEFAULT NULL,
  street varchar(70) DEFAULT NULL,
  house char(20) DEFAULT NULL,
  theme varchar(20) DEFAULT NULL,
  last_failed_login datetime DEFAULT NULL,
  login_attempts int NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `rating`
--
CREATE TABLE IF NOT EXISTS rating (
  id int NOT NULL AUTO_INCREMENT,
  user_id int DEFAULT NULL,
  value tinyint DEFAULT NULL,
  comment varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE rating
ADD CONSTRAINT FK_rating_user_id FOREIGN KEY (user_id)
REFERENCES users (id);

--
-- Create table `organizations`
--
CREATE TABLE IF NOT EXISTS organizations (
  id int NOT NULL AUTO_INCREMENT,
  owner_id int NOT NULL,
  name varchar(50) NOT NULL,
  region varchar(50) DEFAULT NULL,
  city varchar(50) DEFAULT NULL,
  street varchar(70) DEFAULT NULL,
  house char(20) DEFAULT NULL,
  INN varchar(14) NOT NULL,
  couriers tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Are we providing them our couriers?',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE organizations
ADD CONSTRAINT FK_restaurants_owner_id FOREIGN KEY (owner_id)
REFERENCES users (id);

--
-- Create table `account_types`
--
CREATE TABLE IF NOT EXISTS account_types (
  id int NOT NULL AUTO_INCREMENT,
  type varchar(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;